run:
  flex_tag: h2_mean
  prefix: scenario
  name: current

electricity:
  extendable_carriers:
    Link: ['H2 pipeline']
    Store: [H2]

sector:
  hydrogen_fuel_cell: true
  hydrogen_turbine: true
  hydrogen_underground_storage_locations:
  - nearshore
  - onshore
  - offshore
  H2_retrofit: true
  H2_turbine_FOM_Ratio: 1
  H2_turbine_VOM_Ratio: 1
    
