run:
  flex_tag: ror_mean
  prefix: scenario
  name: current

electricity:
  extendable_carriers:
    Generator: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float, OCGT, CCGT, ror]

renewable:
  hydro:
    carriers: [hydro, ror]