run:
  flex_tag: flex_mean
  prefix: scenario
  name: current

# stromimport und export
scenario:
  ll:
  - c1.2

# transmission_projects:
#   enable: true

lines:
  max_extension: 20000 #MW
  length_factor: 1.5
  under_construction: 'keep'

links:
  max_extension: 30000 #MW
  length_factor: 1.5
  under_construction: 'keep'

electricity:
  transmission_limit: 'c1.2'
  extendable_carriers:
    Generator: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float, OCGT, CCGT, biogas]
    Link: ['H2 pipeline']
    Store: [H2, battery]

renewable:
  hydro:
    carriers: [hydro, ror, PHS]

sector:
  hydrogen_fuel_cell: true
  hydrogen_turbine: false
  hydrogen_underground_storage_locations:
  - nearshore
  - onshore
  - offshore
  H2_retrofit: true
  H2_turbine_FOM_Ratio: 1
  H2_turbine_VOM_Ratio: 1
  battery_enable: true
  bev_dsm: true
  v2g: true
  bev_dsm_availability: 0.5
  biogas_enable: true
  biomass_boiler: true
  chp:
    fuel:
    - gas
    - solid biomass
  enhanced_geothermal:
    enable: true
    var_cf: true  