run:
  flex_tag: h2_good
  prefix: scenario
  name: current

electricity:
  extendable_carriers:
    Link: ['H2 pipeline']
    Store: [H2]

sector:
  hydrogen_fuel_cell: true
  hydrogen_turbine: true
  hydrogen_underground_storage_locations:
  - nearshore
  - onshore
  - offshore
  H2_retrofit: true
  H2_turbine_FOM_Ratio: 0.8
  H2_turbine_VOM_Ratio: 0.8

costs:
  override:
    electrolysis:
      efficiency: 0.6994
      FOM: 4
      investment: 990
      lifetime: 27.5
    fuel cell:
      efficiency: 0.525
      FOM: 5
      investment: 846.5773
      lifetime: 11
    hydrogen storage underground:
      investment: 1.2699
      lifetime: 110
    H2 (g) pipeline repurposed:
      FOM: 1.5
      investment: 103.57456
      lifetime: 55
    H2 (g) pipeline:
      FOM: 1.5
      investment: 151.8422
      lifetime: 65
    
