run:
  flex_tag: smart_base
  prefix: smart
  name: base

scenario:
  ll:
  - c1.25
  clusters:
  - 27
  opts:
  - 6H
  sector_opts:
  - 6H
  planning_horizons:
  - 2045

countries: ['AT', 'BE', 'CH', 'CZ', 'DE', 'DK', 'FR', 'GB', 'LU', 'NL', 'NO', 'PL', 'SE', 'ES', 'IT']

renewable:
  onwind:
    capacity_per_sqkm: 1.4
    cutout: europe-2019-sarah3-era5
    correction_factor: 0.95
  offwind-ac:
    capacity_per_sqkm: 6
    landfall_length: 30
    cutout: europe-2019-sarah3-era5
    correction_factor: 0.95
  offwind-dc:
    capacity_per_sqkm: 6
    landfall_length: 30
    cutout: europe-2019-sarah3-era5
    correction_factor: 0.95
  offwind-float: # disabled at the moment
    landfall_length: 30
    capacity_per_sqkm: 6
    cutout: europe-2019-sarah3-era5
    correction_factor: 0.95
  solar:
    cutout: europe-2019-sarah3-era5
    correction_factor: 0.9 # scaling to Abbildung 36 of https://www.ise.fraunhofer.de/de/veroeffentlichungen/studien/aktuelle-fakten-zur-photovoltaik-in-deutschland.html
  solar-hsat:
    cutout: europe-2019-sarah3-era5
    correction_factor: 0.9 # scaling to Abbildung 36 of https://www.ise.fraunhofer.de/de/veroeffentlichungen/studien/aktuelle-fakten-zur-photovoltaik-in-deutschland.html
  hydro:
    cutout: europe-2019-sarah3-era5
    carriers: [hydro, PHS]

transmission_projects:
  enable: false

lines:
  max_extension: 20000
  length_factor: 1.5
  under_construction: 'keep'
  dynamic_line_rating:
    cutout: europe-2019-sarah3-era5

links:
  max_extension: 3000
  length_factor: 1.5
  under_construction: 'keep'

co2_budget: 
  2020: 0.720 # average emissions of 2019 to 2021 relative to 1990, excl LULUCF, EEA data, European Environment Agency. (2023a). Annual European Union greenhouse gas inventory 1990–2021 and inventory report 2023 - CRF Table. https://unfccc.int/documents/627830
  2025: 0.648 # With additional measures (WAM) projection, CO2 excl LULUCF, European Environment Agency. (2023e). Member States’ greenhouse gas (GHG) emission projections 2023. https://www.eea.europa.eu/en/datahub/datahubitem-view/4b8d94a4-aed7-4e67-a54c-0623a50f48e8
  2030: 0.450 # 55% reduction by 2030 (Ff55)
  2035: 0.250
  2040: 0.100 # 90% by 2040
  2045: 0.000
  2050: 0.000 # climate-neutral by 2050

snapshots:
  start: "2019-01-01"
  end: "2020-01-01"
  inclusive: 'left'

electricity:
  estimate_renewable_capacities:
    year: 2019
  transmission_limit: 'c1.25'

  extendable_carriers:
    Storage: []
    Store: [battery, H2]


atlite:
  default_cutout: europe-2019-sarah3-era5
  cutouts:
    europe-2019-sarah3-era5:
      module: [sarah, era5] # in priority order
      x: [-12., 42.]
      y: [33., 72]
      dx: 0.3
      dy: 0.3
      time: ['2019', '2019']

solving:
  solver:
    name: gurobi
    options: gurobi-default

costs:
  year: 2045

clustering:
  focus_weights:
   # 27 nodes: 8 for Germany, 3 for Italy, 2 each for Denmark, UK and Spain, 1 per each of other 10 "Stromnachbarn"
    'DE': 0.2966
    'AT': 0.0370
    'BE': 0.0370
    'CH': 0.0370
    'CZ': 0.0370
    'DK': 0.0741
    'FR': 0.0370
    'GB': 0.0741
    'LU': 0.0370
    'NL': 0.0370
    'NO': 0.0370
    'PL': 0.0370
    'SE': 0.0370
    'ES': 0.0741
    'IT': 0.1111

sector:
  h2_network: true
  hydrogen_turbine: true
  hydrogen_fuel_cell: true
  enhanced_geothermal:
    enable: true
    var_cf: true
  biomass_spatial: true
  biomass_boiler: true
  co2_spatial: true
  gas_network: true # may be wrong
  methanol:
    regional_methanol_demand: true
  regional_oil_demand: true
  regional_coal_demand: true
  regional_nuclear_demand: true
  regional_oil_production: true
  bev_dsm: true
  v2g: true
  tes: true
  biogas_enable: true
  battery_enable: true
  h2_store_enable: true
  chp:
    fuel:
    - gas
    - solid biomass