run:
  flex_tag: smart_flex
  prefix: smart
  name: current

electricity:
  extendable_carriers:
    Store: [battery, H2]

sector:
  tes: true
  battery_enable: true
  h2_store_enable: true
  bev_dsm_availability: 0.5
  heat_pump_enable: true
  v2g: true
  bev_dsm: true
  # bev_avail_max: 0.16
  # bev_avail_mean: 0.08


solving:
  agg_p_nom_limits:
    agg_offwind: true
    include_existing: false
    file: research/config/smart/agg_p_nom_minmax_2045.csv
  
  constraints: 
    CCL: true